# Generated by Django 4.2 on 2026-03-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablaApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('color', models.CharField(default='Normal', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='ofimatica1',
            table='ofimatica1',
        ),
    ]
