# Generated by Django 4.1.13 on 2026-05-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablaApi', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
