# Generated by Django 4.1.13 on 2026-05-30 21:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id_campana', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campana', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'campana',
            },
        ),
        migrations.CreateModel(
            name='Ceco',
            fields=[
                ('id_ceco', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ceco', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'cecos',
            },
        ),
        migrations.CreateModel(
            name='Cliente2',
            fields=[
                ('id_cliente2', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente2', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'clientes2',
            },
        ),
        migrations.CreateModel(
            name='Codigoceco',
            fields=[
                ('id_codigoceco', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigoceco', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'codigoscecos',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'direcciones',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id_division', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('division', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='MovimientoExtension',
            fields=[
                ('id_movimiento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket', models.TextField(blank=True, null=True)),
                ('extension', models.CharField(max_length=10)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('division', models.CharField(blank=True, max_length=50, null=True)),
                ('plataforma', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_movimiento', models.CharField(choices=[('ASIGNACION', 'ASIGNACION'), ('REASIGNACION', 'REASIGNACION'), ('TRASLADO', 'TRASLADO'), ('LIBERACION', 'LIBERACION')], max_length=20)),
                ('marca', models.CharField(choices=[('CREAR', 'CREAR'), ('TRASLADAR', 'TRASLADAR'), ('LIBERAR', 'LIBERAR')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movimientos_extensiones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id_plataforma', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plataforma', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'plataformas',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sede', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'sedes',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'tipos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=40)),
                ('cedula', models.CharField(max_length=15)),
                ('usuario', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id_extension', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extension', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='La extensión debe ser numérica', regex='^\\d+$')])),
                ('puesto_trabajo', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_ultima_modificacion', models.DateField(auto_now=True)),
                ('ticket_solicitud', models.TextField(blank=True, null=True)),
                ('ticket_eliminacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=15, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_campana', models.ForeignKey(blank=True, db_column='id_campana', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extensiones', to='extensiones.campana')),
                ('id_ceco', models.ForeignKey(blank=True, db_column='id_ceco', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extensiones', to='extensiones.ceco')),
                ('id_cliente2', models.ForeignKey(blank=True, db_column='id_cliente2', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extensiones', to='extensiones.cliente2')),
                ('id_codigoceco', models.ForeignKey(blank=True, db_column='id_codigoceco', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extensiones', to='extensiones.codigoceco')),
                ('id_direccion', models.ForeignKey(blank=True, db_column='id_direccion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extensiones', to='extensiones.direccion')),
                ('id_division', models.ForeignKey(blank=True, db_column='id_division', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extensiones', to='extensiones.division')),
                ('id_plataforma', models.ForeignKey(blank=True, db_column='id_plataforma', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extensiones', to='extensiones.plataforma')),
                ('id_sede', models.ForeignKey(blank=True, db_column='id_sede', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extensiones', to='extensiones.sede')),
                ('id_tipo', models.ForeignKey(blank=True, db_column='id_tipo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extensiones', to='extensiones.tipo')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extensiones', to='extensiones.usuario')),
            ],
            options={
                'db_table': 'extensiones',
            },
        ),
    ]
