# Generated by Django 4.2 on 2026-03-16 01:49

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofimatica1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(blank=True, max_length=17, null=True)),
                ('serial', models.CharField(blank=True, max_length=54, null=True)),
                ('usuario', models.CharField(blank=True, max_length=57, null=True)),
                ('software', models.CharField(blank=True, max_length=85, null=True)),
                ('propietario', models.CharField(blank=True, max_length=10, null=True)),
                ('sede', models.CharField(blank=True, max_length=22, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=47, null=True)),
                ('ticket_asignacion', models.CharField(blank=True, max_length=37, null=True)),
                ('ticket_traslado', models.CharField(blank=True, max_length=75, null=True)),
                ('ticket_retiro', models.CharField(blank=True, max_length=21, null=True)),
                ('fecha', models.CharField(blank=True, max_length=20, null=True)),
                ('nueva', models.CharField(blank=True, max_length=72, null=True)),
                ('estado', models.CharField(blank=True, max_length=289, null=True)),
                ('notes', models.CharField(blank=True, max_length=271, null=True)),
                ('observacion', models.CharField(blank=True, max_length=81, null=True)),
            ],
            options={
                'db_table': 'ofimatica_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('licenciamiento', 'Licenciamiento'), ('consulta', 'Consulta'), ('mesa', 'mesa')], default='consulta', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
