# Generated by Django 4.1.13 on 2026-05-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablaApi', '0002_actividad_alter_ofimatica1_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('licenciamiento', 'Licenciamiento'), ('consulta', 'Consulta'), ('mesa', 'Mesa')], default='consulta', max_length=20),
        ),
    ]
